"""add read_more_url column to index_carouself_items table

Revision ID: 215e8f200
Revises: 4fdd84f5b2e
Create Date: 2015-11-10 20:39:23.293869

"""

# revision identifiers, used by Alembic.
revision = '215e8f200'
down_revision = '4fdd84f5b2e'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('index_carousel_items', sa.Column('read_more_url', sa.String(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('index_carousel_items', 'read_more_url')
    ### end Alembic commands ###
