"""policies table

Revision ID: 2b03efef54c2
Revises: 8c033d6b4798
Create Date: 2016-04-11 17:41:10.585574

"""

# revision identifiers, used by Alembic.
revision = '2b03efef54c2'
down_revision = '8c033d6b4798'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policies',
    sa.Column('policy_uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('heading', sa.String(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('policy_uuid', name=op.f('pk_policies'))
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('policies')
    ### end Alembic commands ###
