"""index content and carousel tables

Revision ID: 33a75d55c5f
Revises: 4abb0ccb5c
Create Date: 2015-12-03 14:57:16.522793

"""

# revision identifiers, used by Alembic.
revision = '33a75d55c5f'
down_revision = '4abb0ccb5c'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('index_carousel_items',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('read_more_url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uuid', name=op.f('pk_index_carousel_items'))
    )
    op.create_table('index_content',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('feature_1_title', sa.String(), nullable=False),
    sa.Column('feature_1_image_url', sa.String(), nullable=False),
    sa.Column('feature_1_description', sa.String(), nullable=False),
    sa.Column('feature_1_read_more_url', sa.String(), nullable=False),
    sa.Column('feature_2_title', sa.String(), nullable=False),
    sa.Column('feature_2_image_url', sa.String(), nullable=False),
    sa.Column('feature_2_description', sa.String(), nullable=False),
    sa.Column('feature_2_read_more_url', sa.String(), nullable=False),
    sa.Column('feature_3_title', sa.String(), nullable=False),
    sa.Column('feature_3_image_url', sa.String(), nullable=False),
    sa.Column('feature_3_description', sa.String(), nullable=False),
    sa.Column('feature_3_read_more_url', sa.String(), nullable=False),
    sa.Column('mid_page_heading', sa.String(), nullable=False),
    sa.Column('mid_page_subheading', sa.String(), nullable=False),
    sa.Column('mid_page_text', sa.String(), nullable=False),
    sa.Column('mid_page_text_2', sa.String(), nullable=False),
    sa.Column('mid_page_feature_1_title', sa.String(), nullable=False),
    sa.Column('mid_page_feature_1_image_url', sa.String(), nullable=False),
    sa.Column('mid_page_feature_1_description', sa.String(), nullable=False),
    sa.Column('mid_page_feature_2_title', sa.String(), nullable=False),
    sa.Column('mid_page_feature_2_image_url', sa.String(), nullable=False),
    sa.Column('mid_page_feature_2_description', sa.String(), nullable=False),
    sa.Column('mid_page_feature_3_title', sa.String(), nullable=False),
    sa.Column('mid_page_feature_3_image_url', sa.String(), nullable=False),
    sa.Column('mid_page_feature_3_description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uuid', name=op.f('pk_index_content'))
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('index_content')
    op.drop_table('index_carousel_items')
    ### end Alembic commands ###
