"""another text field colomn for index content mid_page

Revision ID: 43d8997151a
Revises: c843342e14
Create Date: 2015-11-12 20:48:10.418513

"""

# revision identifiers, used by Alembic.
revision = '43d8997151a'
down_revision = 'c843342e14'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('index_content', sa.Column('mid_page_text_2', sa.String(length=600), nullable=True))
    op.execute(text("update index_content set mid_page_text_2 = ''"))
    op.alter_column("index_content", "mid_page_text_2", nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('index_content', 'mid_page_text_2')
    ### end Alembic commands ###
