"""create projects and images and videos tables

Revision ID: 4abb0ccb5c
Revises: 
Create Date: 2015-10-24 12:58:52.662123

"""

# revision identifiers, used by Alembic.
revision = '4abb0ccb5c'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.String(), primary_key=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('avatar_url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    op.create_table('images',
    sa.Column('image_url', sa.String(), primary_key=True, nullable=False),
    sa.Column('thumbnail_url', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_images_project_id_projects')),
    sa.PrimaryKeyConstraint('image_url', name=op.f('pk_images'))
    )
    op.create_index(op.f('ix_images_project_id'), 'images', ['project_id'], unique=False)
    op.create_table('videos',
    sa.Column('video_url', sa.String(), primary_key=True, nullable=False),
    sa.Column('thumbnail_url', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_videos_project_id_projects')),
    sa.PrimaryKeyConstraint('video_url', name=op.f('pk_videos'))
    )
    op.create_index(op.f('ix_videos_project_id'), 'videos', ['project_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_videos_project_id'), table_name='videos')
    op.drop_table('videos')
    op.drop_index(op.f('ix_images_project_id'), table_name='images')
    op.drop_table('images')
    op.drop_table('projects')
    ### end Alembic commands ###
