"""index_carouself_items table

Revision ID: 4fdd84f5b2e
Revises: 4abb0ccb5c
Create Date: 2015-11-10 20:24:03.336036

"""

# revision identifiers, used by Alembic.
revision = '4fdd84f5b2e'
down_revision = '4abb0ccb5c'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('index_carousel_items',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('title', sa.String(length=45), nullable=False),
    sa.Column('description', sa.String(length=220), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uuid', name=op.f('pk_index_carousel_items'))
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('index_carousel_items')
    ### end Alembic commands ###
