"""drop columns in favour for markdown

Revision ID: 8c033d6b4798
Revises: 251f7609b14
Create Date: 2016-04-07 19:40:40.573488

"""

# revision identifiers, used by Alembic.
revision = '8c033d6b4798'
down_revision = '251f7609b14'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('index_content', 'mid_page_text_2')
    op.drop_column('index_content', 'mid_page_subheading')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('index_content', sa.Column('mid_page_subheading', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('index_content', sa.Column('mid_page_text_2', sa.VARCHAR(), autoincrement=False, nullable=False))
    ### end Alembic commands ###
