"""index_content table

Revision ID: c843342e14
Revises: 215e8f200
Create Date: 2015-11-10 21:17:19.086422

"""

# revision identifiers, used by Alembic.
revision = 'c843342e14'
down_revision = '215e8f200'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('index_content',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('feature_1_title', sa.String(length=15), nullable=False),
    sa.Column('feature_1_image_url', sa.String(), nullable=False),
    sa.Column('feature_1_description', sa.String(length=160), nullable=False),
    sa.Column('feature_1_read_more_url', sa.String(), nullable=False),
    sa.Column('feature_2_title', sa.String(length=15), nullable=False),
    sa.Column('feature_2_image_url', sa.String(), nullable=False),
    sa.Column('feature_2_description', sa.String(length=160), nullable=False),
    sa.Column('feature_2_read_more_url', sa.String(), nullable=False),
    sa.Column('feature_3_title', sa.String(length=15), nullable=False),
    sa.Column('feature_3_image_url', sa.String(), nullable=False),
    sa.Column('feature_3_description', sa.String(length=160), nullable=False),
    sa.Column('feature_3_read_more_url', sa.String(), nullable=False),
    sa.Column('mid_page_heading', sa.String(length=40), nullable=False),
    sa.Column('mid_page_subheading', sa.String(length=80), nullable=False),
    sa.Column('mid_page_text', sa.String(length=600), nullable=False),
    sa.Column('mid_page_feature_1_title', sa.String(length=15), nullable=False),
    sa.Column('mid_page_feature_1_image_url', sa.String(), nullable=False),
    sa.Column('mid_page_feature_1_description', sa.String(length=160), nullable=False),
    sa.Column('mid_page_feature_2_title', sa.String(length=15), nullable=False),
    sa.Column('mid_page_feature_2_image_url', sa.String(), nullable=False),
    sa.Column('mid_page_feature_2_description', sa.String(length=160), nullable=False),
    sa.Column('mid_page_feature_3_title', sa.String(length=15), nullable=False),
    sa.Column('mid_page_feature_3_image_url', sa.String(), nullable=False),
    sa.Column('mid_page_feature_3_description', sa.String(length=160), nullable=False),
    sa.PrimaryKeyConstraint('uuid', name=op.f('pk_index_content'))
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('index_content')
    ### end Alembic commands ###
